project:
  type: book
  output-dir: docs
book:
  title: "Psychometric analysis of the Mental Health Continuum-Short Form (MHC-SF)"
  subtitle: "Comparing Rasch, CFA and Mokken models"
  repo-url: "https://github.com/pgmj/ki_irt_mhcsf"
  sidebar:
    style: floating
    search: true
  author:
    - name: 'Magnus Johansson'
      affiliation: 'RISE Research Institutes of Sweden'
      affiliation-url: 'https://ri.se/shic'
      orcid: '0000-0003-1669-592X'
  date: last-modified
  date-format: iso

  chapters:
  - index.qmd
  - rasch.qmd
  - cfa.qmd
  - mokken.qmd

format:
  html:
    toc: true
    toc-depth: 3
    code-tools: false
    code-fold: true
    number-sections: true
    layout-align: left
    page-layout: full
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    linestretch: 1.6
    theme:
      - materia
      - custom.scss
    css: styles.css
    link-external-newwindow: true
    fig-dpi: 96
